// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSettings():Promise<void>;

export function GetBackgroundImageBase64(arg1:string):Promise<string>;

export function GetFullConfig():Promise<main.appConfig>;

export function GetMonitors():Promise<Array<number>>;

export function SaveFullConfig(arg1:main.appConfig):Promise<void>;

export function SelectBackgroundImage():Promise<string>;

export function UpdateNow():Promise<void>;
