// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function GetBackgroundImageBase64(arg1) {
  return window['go']['main']['App']['GetBackgroundImageBase64'](arg1);
}

export function GetFullConfig() {
  return window['go']['main']['App']['GetFullConfig']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function SaveFullConfig(arg1) {
  return window['go']['main']['App']['SaveFullConfig'](arg1);
}

export function SelectBackgroundImage() {
  return window['go']['main']['App']['SelectBackgroundImage']();
}

export function UpdateNow() {
  return window['go']['main']['App']['UpdateNow']();
}
